name: Deployment

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  build-backend:
    name: Deploy backend
    runs-on: ubuntu-latest

    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: abracawhat/backend

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: backend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # - name: Push backend to Dokku
    #   uses: dokku/github-action@master
    #   with:
    #       git_remote_url: ${{ secrets.DOKKU_APP_GIT_URL_BACKEND }}
    #       ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
