name: Deployment

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  build-backend:
    name: Deploy backend
    runs-on: ubuntu-latest

    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: ghcr.io/abdarafi/abracawhat-backend
        flavor: |
          latest=auto
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: backend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [build-backend]
    name: Deploy to Dokku
    runs-on: ubuntu-latest
    steps:
      - name: Create temp repo for dokku
        id: dokku_temp_repo
        run: |
          echo "FROM $IMAGE_URL" > Dockerfile
          git init
          git config user.email "dev@abracawhat.com"
          git config user.name "Abracawhat Dev"
          git add Dockerfile
          git commit -m "Trigger deployment with a temp Dockerfile"
          commit=$(git rev-parse HEAD 2>/dev/null || true)
          echo ::set-output name=commit_sha::$commit
        env:
          IMAGE_URL: ghcr.io/abdarafi/abracawhat-backend:latest
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          command: deploy
          git_remote_url: ${{ secrets.DOKKU_APP_GIT_URL_BACKEND }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          git_push_flags: '--force'
          ci_commit: ${{ steps.dokku_temp_repo.outputs.commit_sha }}
