name: Deployment

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  build-backend:
    name: Deploy backend
    runs-on: ubuntu-latest

    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Push backend to Dokku
      uses: dokku/github-action@master
      with:
          git_remote_url: ${{ secrets.DOKKU_APP_GIT_URL_BACKEND }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
